shadow = false
borders = "outset" # Alternatives are "none" and "simple"

# Base colors are red, green, blue, cyan, magenta, yellow, white and black.
[colors]

	background = "#2E3440"

	# If the terminal doesn't support custom color (like the linux TTY),
	# non-base colors will be skipped.
	shadow     = "#3B4252"
	view       = "111"

	# An array with a single value has the same effect as a simple value.
	primary   = "#5e81ac"
	secondary = "#81a1c1"
    tertiary  = "#88c0d0"

	title_primary   = "#ffaa00"
	title_secondary = "#ffff55"

	highlight          = "#F88"
	highlight_inactive = "#5555FF"

[styles.highlight]
    effects = []
    front = "red"
    back = "inherit_parent"
