shadow = false
borders = "outset" # Alternatives are "none" and "simple"

# Base colors are red, green, blue, cyan, magenta, yellow, white and black.
[colors]

	background = "#0f0f0f"

	# If the terminal doesn't support custom color (like the linux TTY),
	# non-base colors will be skipped.
	shadow     = "#3B4252"
	view       = "#0f0f0f"

	# An array with a single value has the same effect as a simple value.
	primary   = "#ebedf5"
	secondary = "#cc3939"

    # Borders, etc.
    tertiary  = "#ebedf5"

    # The color of the title text.
	title_primary   = "#ffaa00"
	title_secondary = "#ffff55"

	highlight          = "#F88"
	highlight_inactive = "#0f0f0f"

[styles.highlight]
    effects = []
    front = "red"
    back = "inherit_parent"
